// <auto-generated />
using Mango.Services.PracticeCouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.PracticeCouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230909165229_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.PracticeCouponAPI.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeId"));

                    b.Property<string>("ShoeBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShoePrice")
                        .HasColumnType("int");

                    b.Property<int>("ShoeSalePrice")
                        .HasColumnType("int");

                    b.HasKey("ShoeId");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            ShoeId = 1,
                            ShoeBrand = "adidas",
                            ShoePrice = 1200,
                            ShoeSalePrice = 1000
                        },
                        new
                        {
                            ShoeId = 2,
                            ShoeBrand = "adidas",
                            ShoePrice = 1300,
                            ShoeSalePrice = 1200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
